state_dbfile = "igor.sqlite"

[channels]

[channels.console]
class = "Console"
[channels.telegram]
class = "Telegram"

[reactors]

[reactors.fortune]
class = "Fortune"
[reactors.echo]
class = "Echo"
[reactors.catpic]
class = "CatPic"
